@startuml
skinparam style strictuml
skinparam linetype ortho
skinparam dpi 160
skinparam nodesep 35
skinparam ranksep 35

skinparam ArrowThickness 1
skinparam ArrowColor #222

[*] --> НОВЫЙ

НОВЫЙ --> НА_СКЛАДЕ : поступление
НОВЫЙ --> ГОТОВ_К_ПРОДАЖЕ : подготовка

НА_СКЛАДЕ --> ЗАРЕЗЕРВИРОВАН_ДЛЯ_ТЕСТДРАЙВА : назначить тест-драйв
ЗАРЕЗЕРВИРОВАН_ДЛЯ_ТЕСТДРАЙВА --> НА_СКЛАДЕ : завершить тест-драйв

НА_СКЛАДЕ --> ГОТОВ_К_ПРОДАЖЕ : подготовка
ЗАРЕЗЕРВИРОВАН_ДЛЯ_ТЕСТДРАЙВА --> ГОТОВ_К_ПРОДАЖЕ : подготовка

ГОТОВ_К_ПРОДАЖЕ --> ПРОДАН : продажа
НА_СКЛАДЕ --> ПРОДАН : продажа

НА_СКЛАДЕ --> В_СЕРВИСЕ : открыть сервис
ГОТОВ_К_ПРОДАЖЕ --> В_СЕРВИСЕ : открыть сервис
ЗАРЕЗЕРВИРОВАН_ДЛЯ_ТЕСТДРАЙВА --> В_СЕРВИСЕ : открыть сервис

В_СЕРВИСЕ --> НА_СКЛАДЕ : закрыть сервис (без подготовки)
В_СЕРВИСЕ --> ГОТОВ_К_ПРОДАЖЕ : закрыть сервис (была подготовка)

ПРОДАН --> [*]
@enduml